apiVersion: v1
kind: Template
metadata:
  name: rhche-che-monitoring
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhche-prometheus
    name: rhche-prometheus
  spec:
    ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
    - name: 9090-tcp
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      deploymentconfig: rhche-prometheus
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: rhche-prometheus
    name: rhche-prometheus
  spec:
    replicas: 1
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 700
      type: Recreate
    selector:
      app: rhche-prometheus
      deploymentconfig: rhche-prometheus
    template:
      metadata:
        labels:
          app: rhche-prometheus
          deploymentconfig: rhche-prometheus
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: rhche-prometheus
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--storage.tsdb.retention.time=30d'
          ports:
          - containerPort: 9090
            protocol: TCP
          volumeMounts:
          - mountPath: /prometheus
            name: volume-data
          - mountPath: /etc/prometheus/prometheus.yml
            name: volume-config
            subPath: prometheus.yml
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              memory: 128Mi
              cpu: 1m
        - args:
          - -provider=github
          - -http-address=:3000
          - -https-address=
          - -htpasswd-file=/etc/proxy/htpasswd/auth
          - -email-domain=*
          - -upstream=${PROMETHEUS_SVC_URL}
          - -github-org=app-sre
          - -github-team=app-sre-observability
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: client-id
                name: prometheus-proxy-config
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client-secret
                name: prometheus-proxy-config
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                key: cookie-secret
                name: prometheus-proxy-config
          image: quay.io/openshiftio/rhel-rhche-oauth2_proxy:latest
          imagePullPolicy: Always
          name: prometheus-proxy
          ports:
          - containerPort: 3000
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /etc/proxy/htpasswd
            name: app-sre-observability-htpasswd
          resources:
            limits:
              cpu: 400m
              memory: 352Mi
            requests:
              memory: 32Mi
              cpu: 10m
        restartPolicy: Always
        volumes:
        - name: volume-data 
          persistentVolumeClaim:
            claimName: rhche-prometheus-data
        - configMap:
            defaultMode: 420
            name: rhche-prometheus-config
          name: volume-config
        - name: app-sre-observability-htpasswd
          secret:
            secretName: app-sre-observability-htpasswd
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rhche-prometheus-data
    labels:
      app: rhche-prometheus
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
parameters:
- name: IMAGE
  value: quay.io/prometheus/prometheus
- name: IMAGE_TAG
  value: v2.13.0
- name: PROMETHEUS_SVC_URL
  value: ""
