apiVersion: v1
kind: Template
metadata:
  name: rhche-che-monitoring
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhche-prometheus
    name: rhche-prometheus
  spec:
    ports:
    - name: 9090-tcp
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      deploymentconfig: rhche-prometheus
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: rhche-prometheus
    name: rhche-prometheus
  spec:
    replicas: 1
    selector:
      app: rhche-prometheus
      deploymentconfig: rhche-prometheus
    template:
      metadata:
        labels:
          app: rhche-prometheus
          deploymentconfig: rhche-prometheus
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: rhche-prometheus
          ports:
          - containerPort: 9090
            protocol: TCP
          volumeMounts:
          - mountPath: /prometheus
            name: volume-data
          - mountPath: /etc/prometheus/prometheus.yml
            name: volume-config
            subPath: prometheus.yml
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 128Mi
        restartPolicy: Always
        volumes:
        - name: volume-data 
          persistentVolumeClaim:
            claimName: rhche-prometheus-data
        - configMap:
            defaultMode: 420
            name: prometheus-config
          name: volume-config
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rhche-prometheus-data
    labels:
      app: rhche-prometheus
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
parameters:
- name: IMAGE
  value: prom/prometheus
- name: IMAGE_TAG
  value: latest
